// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_publicidadRyR;

namespace api_publicidadRyR.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20221125041517_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api_publicidadRyR.Entitys.Categoria", b =>
                {
                    b.Property<int>("cod_cat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nom_cat")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("cod_cat");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Cliente", b =>
                {
                    b.Property<int>("codigocliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("telefono")
                        .HasColumnType("int");

                    b.HasKey("codigocliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Detalle_venta", b =>
                {
                    b.Property<int>("id_detalle_venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("codigo_venta")
                        .HasColumnType("int");

                    b.Property<int>("id_prod")
                        .HasColumnType("int");

                    b.Property<int>("importe")
                        .HasColumnType("int");

                    b.Property<int?>("juguetesid_prod")
                        .HasColumnType("int");

                    b.Property<string>("producto")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("ventacodigo_venta")
                        .HasColumnType("int");

                    b.HasKey("id_detalle_venta");

                    b.HasIndex("juguetesid_prod");

                    b.HasIndex("ventacodigo_venta");

                    b.ToTable("Detalle_venta");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Juguetes", b =>
                {
                    b.Property<int>("id_prod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cant_prod")
                        .HasColumnType("int");

                    b.Property<int?>("categoriacod_cat")
                        .HasColumnType("int");

                    b.Property<int>("cod_cat")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombreprod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("precio_prod")
                        .HasColumnType("float");

                    b.HasKey("id_prod");

                    b.HasIndex("categoriacod_cat");

                    b.ToTable("Juguetes");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Usuario", b =>
                {
                    b.Property<int>("codigo_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ape_user")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre_user")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo_user");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Venta", b =>
                {
                    b.Property<int>("codigo_venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("clientecodigocliente")
                        .HasColumnType("int");

                    b.Property<int>("codigo_user")
                        .HasColumnType("int");

                    b.Property<int>("codigocliente")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("fech_venta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom_cli")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("total")
                        .HasColumnType("float");

                    b.Property<int?>("usuariocodigo_user")
                        .HasColumnType("int");

                    b.HasKey("codigo_venta");

                    b.HasIndex("clientecodigocliente");

                    b.HasIndex("usuariocodigo_user");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Detalle_venta", b =>
                {
                    b.HasOne("api_publicidadRyR.Entitys.Juguetes", "juguetes")
                        .WithMany("detalle_venta")
                        .HasForeignKey("juguetesid_prod");

                    b.HasOne("api_publicidadRyR.Entitys.Venta", "venta")
                        .WithMany("detalle_venta")
                        .HasForeignKey("ventacodigo_venta");

                    b.Navigation("juguetes");

                    b.Navigation("venta");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Juguetes", b =>
                {
                    b.HasOne("api_publicidadRyR.Entitys.Categoria", "categoria")
                        .WithMany("juguetes")
                        .HasForeignKey("categoriacod_cat");

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Venta", b =>
                {
                    b.HasOne("api_publicidadRyR.Entitys.Cliente", "cliente")
                        .WithMany("venta")
                        .HasForeignKey("clientecodigocliente");

                    b.HasOne("api_publicidadRyR.Entitys.Usuario", "usuario")
                        .WithMany("venta")
                        .HasForeignKey("usuariocodigo_user");

                    b.Navigation("cliente");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Categoria", b =>
                {
                    b.Navigation("juguetes");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Cliente", b =>
                {
                    b.Navigation("venta");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Juguetes", b =>
                {
                    b.Navigation("detalle_venta");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Usuario", b =>
                {
                    b.Navigation("venta");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Venta", b =>
                {
                    b.Navigation("detalle_venta");
                });
#pragma warning restore 612, 618
        }
    }
}
